### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ofirvard** [juanroldanbrz/cloudflare-bypass#1]
Hi, I've been looking for solutions like the one you offer and hoped yours would work,
unfortunately it did not.
I wrote

    CHttpRequester requester = new CHttpRequester();
    requester.get("https://kissanime.ru/");

and recived this

    Warning: Nashorn engine is planned to be removed from a future JDK release
    cloudBypass.UnknownChallengeException
    at cloudBypass.CJavascriptChallengeHelper.solveChallenge(CJavascriptChallengeHelper.java:43)
    at cloudBypass.CChallengeResolve.resolveJavascriptChallenge(CChallengeResolve.java:35)
    at cloudBypass.CChallengeResolve.getPathParams(CChallengeResolve.java:27)
    at cloudBypass.CHttpRequester.get(CHttpRequester.java:37)
    at Main.main(Main.java:30)
    
    Process finished with exit code 0

I hope you have a solution for this.
thank you
Ofir

**Comment by juanroldanbrz** [comment]
Hi Ofir.
I will have a look during the weekend, maybe I can have a solution on
Monday.
Have a nice weekend!

**Comment by GianniAzizi** [comment]
Same problem for me !

**Comment by GianniAzizi** [comment]
@juanroldanbrz do you have find a solution ?

**Comment by juanroldanbrz** [comment]
Hi! Im working on this.
So far I found a python tool which may helps https://github.com/christophetd/CloudFlair 
I will check it out and if t works I will make the port to java.
Have a nice day!

**Comment by brr53** [comment]
Hey did any of you find a proper solution

**Comment by megoRU** [comment]
I have the same error.
Can you fix? @juanroldanbrz
